name: Deployment pipeline
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: List fetched files
        run: |
          ls -al
      - name: Install dependencies
        run: |
          make install
      - name: Lint
        run: |
          make lint
      - name: Tests
        run: |
          make tests
      - name: Format code
        run: |
          make format
    
